name: BuildNextApp
on:
  push:
    branches: [main]

jobs:
  release:
    name: Build and deploy for new release
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run Custom Script
        working-directory: /var/www/behnid_client
        run: |
          git pull origin main
          yarn install
          rm -rf .next
          yarn run deploy
