name: BuildNextApp
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: pull and build
        uses: actions/checkout@v2
        script: |
          cd /var/www/behnid_client
          git pull origin main
          yarn install
          rm -rf .next
          yarn run deploy
